# Generated by Django 4.0.3 on 2022-03-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='id_project',
        ),
    ]
