# Generated by Django 4.0.3 on 2022-03-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='text',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
