# Generated by Django 4.0.3 on 2022-03-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_detail_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='id_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.member'),
        ),
    ]
