# Generated by Django 4.0.3 on 2022-03-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userdetail_id_project_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='id_project',
            new_name='username',
        ),
    ]
