# Generated by Django 4.0.3 on 2022-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_detail_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.CharField(default='', max_length=200)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='upload/certificate')),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='certificate',
        ),
    ]
