# Generated by Django 4.0.3 on 2022-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_certificate_delete_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate',
            new_name='certificateAj',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificateMem1',
            field=models.FileField(blank=True, null=True, upload_to='upload/certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificateMem2',
            field=models.FileField(blank=True, null=True, upload_to='upload/certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificateMem3',
            field=models.FileField(blank=True, null=True, upload_to='upload/certificate'),
        ),
    ]
