# Generated by Django 4.0.3 on 2022-03-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_certificate_certificateaj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate',
        ),
    ]
