# Generated by Django 4.0.3 on 2022-03-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_certificate_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='upload/certificate'),
        ),
    ]
