# Generated by Django 4.0.3 on 2022-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_certificate_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='projectID',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
