# Generated by Django 4.0.3 on 2022-03-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_certificate_certificate_certificateaj_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
