# Generated by Django 4.0.3 on 2022-03-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
