# Generated by Django 4.0.3 on 2022-03-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('certificateAj', models.FileField(blank=True, null=True, upload_to='upload/certificate')),
                ('certificateMem1', models.FileField(blank=True, null=True, upload_to='upload/certificate')),
                ('certificateMem2', models.FileField(blank=True, null=True, upload_to='upload/certificate')),
                ('certificateMem3', models.FileField(blank=True, null=True, upload_to='upload/certificate')),
            ],
        ),
    ]
