# Generated by Django 4.0.3 on 2022-03-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='member2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='member3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
