# Generated by Django 4.0.3 on 2022-03-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_userdetail_member2_alter_userdetail_member3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='member2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='member3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
